# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rough Cane Sugar
email: aleks@daleksfadini .com
description: > # this means to ignore newlines until "baseurl:"
  NY based Electronic Duo, Modern Jazz and Electronica
baseurl: "/RCS" # the subpath of your site, e.g. /blog
url: "http://www.aleksfadini.com" # the base hostname & protocol for your site
twitter_username: afadini
github_username:  aleksfadini

# Build settings
markdown: kramdown
